filter:
    paths: [*, lib/*]

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [tests/*, assets/*]
    php_code_coverage: false
    php_code_sniffer:
        filter:
            paths: [*, lib/*]
        config:
            tab_width:  4
            encoding:   utf8
            standard:   WordPress
    php_loc: true
    php_cs_fixer: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
