filter:
    excluded_paths: [tests/*, assets/*]

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [tests/*, assets/*]
    php_code_coverage: false
    php_code_sniffer:
        filter:
            excluded_paths: [tests/*, assets/*]
        config:
            tab_width:  4
            encoding:   utf8
            standard:   WordPress
            sniffs:
                generic:
                    white_space:
                        disallow_tab_indent_sniff:  false
                        disallow_space_indent_sniff:  false
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
