filter:
    excluded_paths: [tests/*, assets/*]

before_commands:
    - "composer install --prefer-source"
    - "wp --info"
    
tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [tests]
    php_code_sniffer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
